PATCH http://localhost:3001/api/v1/cart/4f69cfd1-5b78-46a8-9c1b-28ac80ff820d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDIyNDFiYy02ZmY5LTQ1MWMtYWZiNS0yZmM3N2Q3YjBlMDEiLCJlbWFpbCI6ImZhdm91ckBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDAwNTg1OCwiZXhwIjoxNzYwMDA5NDU4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.NUDkc9cAEKVIJfsesIMVjyO3fhXg8lLjpJvdNtJTxiQ
