PATCH http://localhost:3001/api/v1/cart/ca51605b-4f77-45ff-82c4-8d39d19936b0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDIyNDFiYy02ZmY5LTQ1MWMtYWZiNS0yZmM3N2Q3YjBlMDEiLCJlbWFpbCI6ImZhdm91ckBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDYwOTY0OCwiZXhwIjoxNzYwNjEzMjQ4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.fSOKk24HFm5z7S4chkOyL6BiuvaiLTdXHWE60-ZVSxE

{
    "quantity": 2
}
