DELETE http://localhost:3001/api/v1/cart/52acb271-088a-4609-9953-c874d9bce11d
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNDIyNDFiYy02ZmY5LTQ1MWMtYWZiNS0yZmM3N2Q3YjBlMDEiLCJlbWFpbCI6ImZhdm91ckBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDYxMDc2OCwiZXhwIjoxNzYwNjE0MzY4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.4Sw1iJWITn4zjh-zjvJKOJg9hOoj_nwZepvmrCAxUuk