POST http://localhost:3001/api/v1/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjUwMmY1Yy05YjMzLTRkNWItYjg2NC0xNTE1M2QzMGRhYmUiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDg3NzQwNSwiZXhwIjoxNzYwODgxMDA1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.vKulqt_DmjlYQ_cp2PLnbow07b7p_NQlqltI0mxfRaI

{
    "name": "Dark Silver Cutlery Set",
    "category": "Utensils",
    "description": "Sustainable fork, knife, spoon set – zero plastic waste.",
    "price": 25.0,
    "stock": 20,
    "imageUrl":
      "https://m.media-amazon.com/images/I/71ovT+ReiYL.jpg"
}