DELETE http://localhost:3001/api/v1/products/a48ac60f-b091-4ac5-9685-fe9aec69d2b3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NjUwMmY1Yy05YjMzLTRkNWItYjg2NC0xNTE1M2QzMGRhYmUiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDYwNzY4MCwiZXhwIjoxNzYwNjExMjgwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.TjJwaZAnurEoO3970diUSl3Ajk99iiVzdPHXkzHICqQ